import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Layout.module.css';
import { useState } from 'react';

import discord from '../public/discord.png';
// import twitter from '../public/twitter.png';
import Discord from '../components/Discord';
import Twitter from '../components/Twitter';

export default function Home() {
  const [platformSelected, setPlatformSelected] = useState('discord');

  const setPlatform = (platform) => {
    setPlatformSelected(platform);
  };

  const showPlatformInstructions = () => {
    if (platformSelected) {
      if (platformSelected === 'discord') {
        return <Discord />;
      }
      if (platformSelected === 'twitter') {
        return <Twitter />;
      }
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Confidence Bot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>The Confidence Bot</h1>
        <p>The only bot that makes you more confident.</p>
        <p>Choose one platform :</p>
        <div className={styles.main__platforms}>
          <div
            className={styles.main__platform__container}
            onClick={() => setPlatform('discord')}
          >
            <Image
              className={styles.main__platform__image}
              src={discord}
              width="200rem"
              height="130rem"
            />
          </div>
          {/* <div
            className={styles.main__platform__container}
            onClick={() => setPlatform('twitter')}
          >
            <Image
              className={styles.main__platform__image}
              src={twitter}
              width="200rem"
              height="200rem"
            />
          </div> */}
        </div>
        <div>{showPlatformInstructions()}</div>
        <div className={styles.how}>
          <h2>How does it work ?</h2>
          <p>
            The confidence bot will send one random positive phrase every{' '}
            <span className={styles.discord__description__frequency}>hour</span>
            ,{' '}
            <span className={styles.discord__description__frequency}>day</span>,{' '}
            <span className={styles.discord__description__frequency}>week</span>{' '}
            or{' '}
            <span className={styles.discord__description__frequency}>
              month
            </span>{' '}
            to help you gain confidence, as if it worked like this lol. <br />
            You can unsubscribe from the bot by typing the command{' '}
            <span className={styles.discord__description__command}>
              /unsubscribe
            </span>
            .
          </p>
        </div>
        <div className={styles.how} id="how">
          <h2>Contact</h2>
          <p>
            Instagram :{' '}
            <a
              href="http://www.instagram.com/thejinca"
              className={styles.contact__link}
            >
              @thejinca
            </a>
          </p>
          <p>
            Mail :{' '}
            <a
              href="mailto:http://www.instagram.com/thejinca"
              className={styles.contact__link}
            >
              jinca.contact@gmail.com
            </a>
          </p>
          <p>
            Youtube :{' '}
            <a
              href="http://www.youtube.com/thejinca"
              className={styles.contact__link}
            >
              Jinca
            </a>
          </p>
          <p>
            Twitter :{' '}
            <a
              href="http://www.twitter.com/thejinca"
              className={styles.contact__link}
            >
              TheJinca
            </a>
          </p>
        </div>
      </main>
    </div>
  );
}
